name: 'rosan'
version: '1.0.0'
config-version: 2

profile: 'default'

source-paths: ["definitions"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
    - "target"
    - "dbt_modules"

definitions:
  snowflake_workshop:
    raw:
      materialized: 
      snowflake_warehouse: pc_dbt_wh
    clean:
      materialized: view
      snowflake_warehouse: pc_dbt_wh
    model:
      materialized: table
      snowflake_warehouse: pc_dbt_wh