name: 'rosan'
version: '1.0.0'
config-version: 2

profile: 'sf-dbt-test'

model-paths: ["definitions"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
    - "target"
    - "dbt_modules"

models:
  snowflake_project:
    # Applies to all files under models/.../
    clean:
      materialized: view
      database: data_evolution_admin
      snowflake_warehouse: pc_dbt_wh
    model:
      materialized: table
      database: data_evolution_admin
      snowflake_warehouse: pc_dbt_wh